#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2.84kB 0.0s done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/node:22-alpine
#2 ...

#3 [auth] library/node:pull token for registry-1.docker.io
#3 DONE 0.0s

#2 [internal] load metadata for docker.io/library/node:22-alpine
#2 DONE 1.2s

#4 [internal] load .dockerignore
#4 transferring context: 393B done
#4 DONE 0.0s
Check complete, no warnings found.
