#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 2.81kB done
#1 DONE 0.2s

#2 [auth] library/node:pull token for registry-1.docker.io
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node:22-alpine
#3 DONE 1.0s

#4 [internal] load .dockerignore
#4 transferring context: 433B done
#4 DONE 0.1s
Check complete, no warnings found.
